=== ds-wizard/ds-km/old/datamodel-v1-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://dtls.nl/schemas/dmp-knowledge-model/",
    "type": "object",
    "title": "chapter",
    "description": "JSON file describing a single chapter in the knowledge model for DMP questionnaires",

    "definitions": {
	"chapterid": {
	    "type": "integer",
	    "minimum": 1,
	    "maximum" : 7
	},
	"questionid": {
	    "type": "integer",
	    "minimum": 1
	},
	"namespace": {
	    "type": "string"
	},	    
	"expert": {
	    "type": "object",
	    "properties": {
		"name": { "type": "string" },
		"email": { "type": "string" },
		"class": { "type": "string",
			   "enum": ["individual", "organisation"],
			   "default": "organisation" }
	    },
	    "required": ["name"]
	},
	"experts": {
	    "type": "array",
	    "items": { "$ref": "#/definitions/expert" }
	},
	"questionpointer": {
	    "type": "object",
	    "properties": { 
		"chapterid": { "$ref": "#/definitions/chapterid" },
		"questionid": { "$ref": "#/definitions/questionid" },
		"namespace" : { "$ref": "#/definitions/namespace" }
	    },
	    "required": ["chapterid", "questionid", "namespace"],
	    "additionalProperties": false
	},
	"dmpbookreference": {
	    "type": "object",
	    "properties": {
		"type" : { "type": "string", "enum" : ["dmpbook"] },
		"chapter": { "type": "string" }
	    },
	    "required" : ["type", "chapter"],
	    "additionalProperties": false
	},
	"urlreference": {
	    "type": "object",
	    "properties": {
		"type" : { "type": "string", "enum" : ["url"] },
		"url": {"type": "string" },
		"anchor": {"type": "string" }
	    },
	    "required" : ["type", "weblink"],
	    "additionalProperties": false
	},
	"crossreference": {
	    "type": "object",
	    "properties": {
		"type" : { "type": "string", "enum" : ["xref"] },
		"chapterid": { "$ref": "#/definitions/chapterid" },
		"questionid": { "$ref": "#/definitions/questionid" },
		"namespace" : { "$ref": "#/definitions/namespace" }
	    },
	    "required": ["chapterid", "questionid"],
	    "additionalProperties": false
	},
	"reference": {
	    "anyOf": [
		{ "$ref": "#/definitions/dmpbookreference" },
		{ "$ref": "#/definitions/urlreference" },
		{ "$ref": "#/definitions/crossreference" }
	    ]
	},
	"references": {
	    "type": "array",
	    "items": { "$ref": "#/definitions/reference" }
	},
	"answerid": {
	    "type": "integer",
	    "minimum": 0
	},
	"optionanswer": {
	    "type": "object",
	    "properties": {
		"id": { "$ref" : "#/definitions/answerid" },
		"label": { "type": "string" },
		"advice": { "type": "string" }
	    },
	    "required": [ "id", "label"],
	    "additionalProperties": false
	},
	"optionanswers": {
	    "type": "array",
	    "items": { "$ref": "#/definitions/optionanswer" }
	},
	"precondition": {
	    "type": "object",
	    "properties": {
		"namespace": { "$ref": "#/definitions/namespace" },
		"questionid": { "$ref": "#/definitions/questionid" },
		"answerid": { "$ref": "#/definitions/answerid" }
	    },
	    "required": [ "questionid"],
	    "additionalProperties": false
	},
	"question": {
	    "type": "object",
	    "properties": {
		"questionid": { "$ref": "#/definitions/questionid" },
		"namespace": { "$ref": "#/definitions/namespace" },
		"precondition": { "$ref": "#/definitions/precondition" },
		"insertBefore": { "$ref": "#/definitions/questionpointer" },
		"references": { "$ref": "#/definitions/references" },
		"addReferences": { "$ref": "#/definitions/references" },
		"experts": { "$ref": "#/definitions/experts" },
		"addExperts": { "$ref": "#/definitions/experts" },		
		"type": {
		    "type": "string",
		    "enum": ["option", "list", "string", "text"]
		},
		"title": { "type": "string" },
		"text": { "type": "string" },
		"answers": { "$ref": "#/definitions/optionanswers" },
		"addAnswers": { "$ref": "#/definitions/optionanswers" }		
	    },
	    "required": ["questionid"],
	    "additionalProperties": false
	},
	"optionquestion": {
	    "type": "object",
	    "properties": {
		"type": {
		    "type": "string",
		    "enum": ["option"]
		},
		"answers": { "minItems": 1 }
	    }
	},
	"fieldquestion": {
	    "type": "object",
	    "properties": {
		"type": {
		    "type": "string",
		    "enum": ["list", "string", "text"]
		},
		"answers": { "maxItems": 0 }
	    }
	}	    
    },
    
    "properties": {
	"chapterid": { "$ref": "#/definitions/chapterid" },
	"namespace": { "$ref": "#/definitions/namespace" },
	"formatversion": {
	    "type": "integer",
	    "minimum": 1,
	    "maximum": 1
	},
	"title": { "type": "string" },
	"text": { "type": "string" },
	"questions": {
	    "type": "array",
	    "items": {
		"allOf": [
		    { "$ref": "#/definitions/question" },
		    {
			"anyOf": [
			    { "$ref": "#/definitions/optionquestion" },
			    { "$ref": "#/definitions/fieldquestion" }
			]
		    }
		]
	    }
	}
    },
    "required": [
	"chapterid",
	"namespace",
	"formatversion",
	"questions"
    ],
    "additionalProperties": false
}

=== ds-wizard/ds-km/datamodel/core/chapter5.json
{
    "chapterid": 5,
    "namespace": "core",
    "formatversion": 1,
    "title": "Data integration",
    "questions" :
    [
	{
	    "questionid": 1, "type": "option",
	    "title": "How will you be doing the integration of different data sources?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "This as been taken care of" },
		{   "id": 1, "label": "Explore this with additional questions" }
	    ]
	},
	{
	    "questionid": 6, "type": "option",
	    "precondition": { "questionid": 1, "answerid": 1 },
	    "title": "What kind of framework will you use?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "Spreadsheets like Microsoft Excel" },
		{   "id": 1, "label": "A regular tabular database" },
		{   "id": 2, "label": "A graph database" },
		{   "id": 3, "label": "RDF" },
		{   "id": 4, "label": "(meta)data fields in a domain specific file" },
		{   "id": 98, "label": "A combination of the above" },
		{   "id": 99, "label": "We have made other arrangements" }
	    ]
	},
	{
	    "questionid": 7, "type": "text",
	    "precondition": {"questionid": 6, "answerid": 99},
	    "title": "What other arrangements?"
	},
	{
	    "questionid": 8, "type": "option",
	    "precondition": { "questionid": 1, "answerid": 1 },
	    "title": "Will you be using a workflow for data integration, e.g. with tools for database access or conversion?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes" }
	    ],
            "references": [{ "type": "dmpbook", "chapter": "5.3" }]
	},
	{
	    "questionid": 9, "type": "option",
	    "precondition": { "questionid": 1, "answerid": 1 },
	    "title": "Will you use a 'linked data' approach?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes" }
	    ]
	},
	{
	    "questionid": 10, "type": "option",
	    "precondition": { "questionid": 9, "answerid": 1 },
	    "title": "Are your data sources using linked data?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Partly" },
		{   "id": 2, "label": "Yes" }
	    ]
	},
	{
	    "questionid": 11, "type": "option",
	    "precondition": { "questionid": 9, "answerid": 1 },
	    "title": "Will you provide your results as semantically interoperable linked data?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes" }
	    ],
            "references": [{ "type": "dmpbook", "chapter": "5.2" }]
	},
	{
	    "questionid": 2, "type": "option",
	    "title": "Will you be using common or exchangeable units?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes" }
	    ]
	},
	{
	    "questionid": 3, "type": "option",
	    "title": "Will you be using common ontologies?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes", "advice": "Choose the ontologies before you start" }
	    ]
	},
	{
	    "questionid": 4, "type": "option",
	    "title": "Will there be potential issues with statistical normalization?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes" }
	    ]
	},
	{
	    "questionid": 12, "type": "option",
	    "title": "Will you be integrating different data sources to get more samples or more data points?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes" }
	    ]
	},
	{
	    "questionid": 14, "type": "option",
	    "precondition": { "questionid": 12, "answerid": 1 },
	    "title": "Have these been collected with sufficiently identical protocols?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes" }
	    ]
	},
	{
	    "questionid": 13, "type": "option",
	    "title": "Will you be integrating different data sources in order to get more information for each sample or data point?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes" }
	    ]
	},
	{
	    "questionid": 15, "type": "option",
	    "precondition": { "questionid": 13, "answerid": 1 },
	    "title": "Did you already select the variables on which you will join the data sets?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes" }
	    ]
	},
	{
	    "questionid": 16, "type": "option",
	    "precondition": { "questionid": 13, "answerid": 1 },
	    "title": "Will you make sure that you do not inadvertently create a biased subset?",
	    "text": "Some parameters you select on may have been collected only for a subset of the subjects or data points. An obvious example is if you match on secondary education type, you will bias to people over 18 years old because younger people do not have this field. In many cases the selection bias may be a lot less obvious and special measures exist to verify that the diversity of the sample is not reduced by the integration step.",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes" }
	    ]
	},
	{
	    "questionid": 17, "type": "option",
	    "precondition": { "questionid": 13, "answerid": 1 },
	    "title": "Could the coupling of data create a danger of re-identification of anonymized privacy sensitive data?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes", "advice": "Plan either preventative or corrective measures" }
	    ]
	},
	{
	    "questionid": 18, "type": "option",
	    "precondition": { "questionid": 13, "answerid": 1 },
	    "title": "Did you make a conscious decision to be either accurate or complete?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes" }
	    ]
	},
	
	{
	    "questionid": 5, "type": "option",
	    "title": "Do you have all tools to couple the necessary data types?",
	    "answers": 
	    [ 
		{   "id": 0, "label": "No" },
		{   "id": 1, "label": "Yes" }
	    ]
	}
    ]
}
